using System;
using System.Data;
using System.Data.SqlClient;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Net;
using System.IO;

namespace Group11Unishare
{
    public partial class Register : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                lblMessage.Text = "";
                LoadUniversities();
                LoadRoles();
            }
        }

        private bool ValidateReCaptcha()
        {
            // Grab the token generated by the checkbox
            string captchaResponse = Request.Form["g-recaptcha-response"];

            if (string.IsNullOrEmpty(captchaResponse))
            {
                return false; // They didn't even click the checkbox
            }

            bool isValid = false;
            string secretKey = "6LeMXOksAAAAAIzerGkJ1wlT33MNRIas5JsrTX2y";

            // Create the secure request to Google's API
            string apiUrl = $"https://www.google.com/recaptcha/api/siteverify?secret={secretKey}&response={captchaResponse}";
            HttpWebRequest req = (HttpWebRequest)WebRequest.Create(apiUrl);

            try
            {
                using (WebResponse wResponse = req.GetResponse())
                {
                    using (StreamReader readStream = new StreamReader(wResponse.GetResponseStream()))
                    {
                        string jsonResponse = readStream.ReadToEnd();

                        // A quick, pure .NET way to check the JSON without installing external packages
                        if (jsonResponse.Contains("\"success\": true"))
                        {
                            isValid = true;
                        }
                    }
                }
            }
            catch
            {
                // If Google's servers are down, default to false for security
                return false;
            }

            return isValid;
        }

        // --- Cascading Dropdown Logic ---
        private void LoadUniversities()
        {
            ddlUniversity.Items.Clear();
            ddlUniversity.Items.Add(new ListItem("-- Select your university --", ""));

            try
            {
                // FIXED: Now using your secure DatabaseHelper!
                using (SqlConnection conn = DatabaseHelper.GetConnection())
                {
                    string query = "SELECT universityID, universityName FROM University ORDER BY universityName";
                    using (SqlCommand cmd = new SqlCommand(query, conn))
                    {
                        conn.Open();
                        using (SqlDataReader reader = cmd.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                ddlUniversity.Items.Add(new ListItem(reader["universityName"].ToString(), reader["universityID"].ToString()));
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ShowMessage("Error loading universities: " + ex.Message, false);
            }
        }

        private void LoadRoles()
        {
            ddlRole.Items.Clear();
            ddlRole.Items.Add(new ListItem("-- Select your role --", ""));

            try
            {
                // FIXED: Now using your secure DatabaseHelper!
                using (SqlConnection conn = DatabaseHelper.GetConnection())
                {
                    string query = "SELECT RoleID, RoleName FROM Role ORDER BY RoleName DESC";
                    using (SqlCommand cmd = new SqlCommand(query, conn))
                    {
                        conn.Open();
                        using (SqlDataReader reader = cmd.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                ddlRole.Items.Add(new ListItem(reader["RoleName"].ToString(), reader["RoleID"].ToString()));
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ShowMessage("Error loading roles: " + ex.Message, false);
            }
        }

        protected void ddlUniversity_SelectedIndexChanged(object sender, EventArgs e)
        {
            ddlCampus.Items.Clear();

            if (string.IsNullOrEmpty(ddlUniversity.SelectedValue))
            {
                ddlCampus.Items.Add(new ListItem("-- Select a university first --", ""));
                ddlCampus.Enabled = false;
            }
            else
            {
                ddlCampus.Enabled = true;
                ddlCampus.Items.Add(new ListItem("-- Select your campus --", ""));

                string selectedUniId = ddlUniversity.SelectedValue;

                try
                {
                    // FIXED: Now using your secure DatabaseHelper!
                    using (SqlConnection conn = DatabaseHelper.GetConnection())
                    {
                        string query = "SELECT campusID, campusName FROM Campus WHERE universityID = @UniversityID ORDER BY campusName";
                        using (SqlCommand cmd = new SqlCommand(query, conn))
                        {
                            cmd.Parameters.AddWithValue("@UniversityID", selectedUniId);
                            conn.Open();
                            using (SqlDataReader reader = cmd.ExecuteReader())
                            {
                                while (reader.Read())
                                {
                                    ddlCampus.Items.Add(new ListItem(reader["campusName"].ToString(), reader["campusID"].ToString()));
                                }
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    ShowMessage("Error loading campuses: " + ex.Message, false);
                }
            }
        }

        // --- Form Submission Logic ---
        protected void btnRegister_Click(object sender, EventArgs e)
        {
            // 1. RECAPTCHA SECURITY CHECK FIRST!
            if (!ValidateReCaptcha())
            {
                lblMessage.Text = "Security Check Failed: Please verify that you are not a robot.";
                lblMessage.CssClass = "text-danger fw-bold d-block mb-3 text-center";
                return;
            }

            if (string.IsNullOrEmpty(ddlRole.SelectedValue))
            {
                ShowMessage("Please select an account type.", false);
                return;
            }

            if (string.IsNullOrWhiteSpace(txtFullName.Text) ||
                string.IsNullOrWhiteSpace(txtEmail.Text) ||
                string.IsNullOrWhiteSpace(txtPassword.Text))
            {
                ShowMessage("Please fill in all required fields.", false);
                return;
            }

            if (string.IsNullOrEmpty(ddlUniversity.SelectedValue))
            {
                ShowMessage("Please select your university.", false);
                return;
            }

            if (string.IsNullOrEmpty(ddlCampus.SelectedValue))
            {
                ShowMessage("Please select your primary campus.", false);
                return;
            }

            if (txtPassword.Text != txtConfirmPassword.Text)
            {
                ShowMessage("Passwords do not match!", false);
                return;
            }

            if (!chkTerms.Checked)
            {
                ShowMessage("You must agree to the Terms and Conditions to register.", false);
                return;
            }

            try
            {
                // FIXED: Now using your secure DatabaseHelper!
                using (SqlConnection conn = DatabaseHelper.GetConnection())
                {
                    // FIXED: Added dateRegistered and isAdmin to prevent SQL crashes
                    string query = @"INSERT INTO UserDetails (userName, email, userPassword, campusID, RoleID, dateRegistered, isAdmin) 
                                     VALUES (@Name, @Email, @Password, @CampusID, @RoleID, GETDATE(), 0)";

                    using (SqlCommand cmd = new SqlCommand(query, conn))
                    {
                        cmd.Parameters.AddWithValue("@Name", txtFullName.Text.Trim());
                        cmd.Parameters.AddWithValue("@Email", txtEmail.Text.Trim());
                        cmd.Parameters.AddWithValue("@Password", txtPassword.Text);
                        cmd.Parameters.AddWithValue("@CampusID", ddlCampus.SelectedValue);
                        cmd.Parameters.AddWithValue("@RoleID", ddlRole.SelectedValue);

                        conn.Open();
                        cmd.ExecuteNonQuery();
                    }
                }

                Response.Redirect("Login.aspx");
            }
            catch (SqlException sqlEx)
            {
                ShowMessage("SQL Error: " + sqlEx.Message, false);
            }
        }

        protected void btnClear_Click(object sender, EventArgs e)
        {
            ClearForm();
            ShowMessage("", true);
        }

        private void ClearForm()
        {
            txtFullName.Text = string.Empty;
            txtEmail.Text = string.Empty;
            txtPassword.Text = string.Empty;
            txtConfirmPassword.Text = string.Empty;

            ddlUniversity.SelectedIndex = 0;

            ddlCampus.Items.Clear();
            ddlCampus.Items.Add(new ListItem("-- Select a university first --", ""));
            ddlCampus.Enabled = false;

            chkTerms.Checked = false;
        }

        private void ShowMessage(string message, bool isSuccess)
        {
            lblMessage.Text = message;
            lblMessage.CssClass = isSuccess ? "fw-bold text-success mt-2" : "fw-bold text-danger mt-2";
        }
    }
}